### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by LucasLeandro1204** [LucasLeandro1204/vue-snippets#1]
We need a better readme xd

Currently we have one component, but why not have the structure for when we have a thousand?

**Comment by krb1997** [comment]
Can help with this :)

**Comment by LucasLeandro1204** [comment]
nice @krb1997, I'll be waiting for.

**Comment by krb1997** [comment]
No worries, I have something to push up. Could i get a Development branch?

**Comment by LucasLeandro1204** [comment]
@krb1997 Fork the repo, create a readme branch, push whatever you want and then open de pr

**Comment by krb1997** [comment]
@LucasLeandro1204 Have a pull request in for your view plesure :)

**Comment by LucasLeandro1204** [comment]
@krb1997 reviewed xd
