### ISSUE TITLE
Donation Gif

### ISSUE THREAD

**Issue by LucasLeandro1204** [LucasLeandro1204/vue-snippets#11]
Add a demonstration Gif for donation component in Readme.

**Comment by LucasLeandro1204** [comment]
You don't even have to setup this project, you can [go here](https://lucasleandro1204.github.io/vue-snippets/).

**Comment by emilyy1231** [comment]
Got it

**Comment by LucasLeandro1204** [comment]
@emilyy1231 nice =)
